services:
  springboot:
    image: openjdk:20-jdk-slim
    container_name: fromis_9-springboot
    expose:
      - "8080"
    working_dir: /app
    entrypoint: ["java", "-jar", "fromis_9.jar"]
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      FAST_API_URL: ${FAST_API_URL}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    networks:
      - app
    restart: always

networks:
  app:
    name: app
    driver: bridge